### ISSUE TITLE
Fix intermittant conda-related failures of GitHub Actions

### ISSUE THREAD

**Issue by matthuska** [rki-mf1/clean#93]
Here is an example error from "[Dry run illumina-conda-nf_23.04.1 pipeline test](https://github.com/rki-mf1/clean/actions/runs/9174822688/job/25226486882#logs)"
```
ERROR ~ Error executing process > 'prepare_contamination:prepare_own_host:check_own (1)'
  
  Caused by:
    Failed to create Conda environment
    command: conda env create --prefix /home/runner/work/clean/clean/.nf-test/tests/5404054a073af610188ce52d5f4d8f82/conda/seqkit-1b871fab0dd87fed2fd1229f71a0d822 --file /home/runner/work/clean/clean/envs/seqkit.yaml
    status : 1
    message:
      InvalidArchiveError("Error with archive /home/runner/conda_pkgs_dir/libstdcxx-ng-13.2.0-hc0a3c3a_7.conda.  You probably need to delete and re-download or re-create this file.  Message was:\n\nfailed with error: [Errno 2] No such file or directory: '/home/runner/conda_pkgs_dir/libstdcxx-ng-13.2.0-hc0a3c3a_7.conda'")
```

**Comment by hoelzer** [comment]
I think this was fixed @matthuska ?

**Comment by matthuska** [comment]
I still see a few actions failing with conda-related messages. I'll tweak some of the conda env files and also the CI workflow config to see if I can resolve the problem.
